//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmCentralStock.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Employee_Type_Id { get; set; }

        [Required(ErrorMessage ="* Name field is Required.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "* Surname field is Required.")]
        public string Surname { get; set; }
        public string Contact { get; set; }
    
        public virtual User_Role User_Role { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
    }
}
