//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmCentralStock.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_List
    {
        public int Id { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public Nullable<int> Farmer_ID { get; set; }

        [Required(ErrorMessage = "* Product Name field is Required.")]
        public string Product_Name { get; set; }

        [Required(ErrorMessage = "* Price field is Required.")]
        public Nullable<decimal> Price { get; set; }

        [Required(ErrorMessage = "* Quantity field is Required.")]
        public Nullable<int> Quantity { get; set; }

        [Required(ErrorMessage = "* Date field is Required.")]
        public Nullable<System.DateTime> Date_Registered { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        public virtual Product_Type Product_Type { get; set; }
    }
}
